apiVersion: v1
kind: Service
metadata:
  name: python-helloworld-service
  namespace: python-helloworld
  labels:
    app: python-helloworld
spec:
  selector:
    app: python-helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
